# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mspfilemanager.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.groupBox)
        self.addButton.setMinimumSize(QtCore.QSize(80, 60))
        self.addButton.setMaximumSize(QtCore.QSize(80, 60))
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 1, 1, 1)
        self.editButton = QtWidgets.QPushButton(self.groupBox)
        self.editButton.setMinimumSize(QtCore.QSize(80, 60))
        self.editButton.setMaximumSize(QtCore.QSize(80, 60))
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 1, 2, 1, 1)
        self.removeButton = QtWidgets.QPushButton(self.groupBox)
        self.removeButton.setMinimumSize(QtCore.QSize(80, 60))
        self.removeButton.setMaximumSize(QtCore.QSize(80, 60))
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 3, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.zoomButton = QtWidgets.QPushButton(self.groupBox_4)
        self.zoomButton.setObjectName("zoomButton")
        self.gridLayout_3.addWidget(self.zoomButton, 0, 0, 1, 1)
        self.panButton = QtWidgets.QPushButton(self.groupBox_4)
        self.panButton.setObjectName("panButton")
        self.gridLayout_3.addWidget(self.panButton, 0, 1, 1, 1)
        self.rescaleButton = QtWidgets.QPushButton(self.groupBox_4)
        self.rescaleButton.setObjectName("rescaleButton")
        self.gridLayout_3.addWidget(self.rescaleButton, 0, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(550, 500))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox.raise_()
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFind_similar_spectra = QtWidgets.QAction(MainWindow)
        self.actionFind_similar_spectra.setObjectName("actionFind_similar_spectra")
        self.actionFind_MS_MS_spectra = QtWidgets.QAction(MainWindow)
        self.actionFind_MS_MS_spectra.setObjectName("actionFind_MS_MS_spectra")
        self.actionClean_MS_MS_spectra = QtWidgets.QAction(MainWindow)
        self.actionClean_MS_MS_spectra.setObjectName("actionClean_MS_MS_spectra")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionFind_MS_MS_spectra)
        self.menuTools.addAction(self.actionFind_similar_spectra)
        self.menuTools.addAction(self.actionClean_MS_MS_spectra)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MSP File Manager"))
        self.groupBox.setTitle(_translate("MainWindow", "MS/MS spectra list"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.removeButton.setText(_translate("MainWindow", "Remove"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot options"))
        self.zoomButton.setText(_translate("MainWindow", "Zoom"))
        self.panButton.setText(_translate("MainWindow", "Pan"))
        self.rescaleButton.setText(_translate("MainWindow", "Rescale"))
        self.checkBox.setText(_translate("MainWindow", "Relative intensity"))
        self.groupBox_2.setTitle(_translate("MainWindow", "MS/MS Spectra view"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Compounds fields"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFind_similar_spectra.setText(_translate("MainWindow", "Find similar spectra"))
        self.actionFind_MS_MS_spectra.setText(_translate("MainWindow", "Find MS/MS spectra"))
        self.actionClean_MS_MS_spectra.setText(_translate("MainWindow", "Clean spectra"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))

