# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compoundspectra.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CompoundSpectraDialog(object):
    def setupUi(self, CompoundSpectraDialog):
        CompoundSpectraDialog.setObjectName("CompoundSpectraDialog")
        CompoundSpectraDialog.resize(500, 480)
        CompoundSpectraDialog.setMaximumSize(QtCore.QSize(500, 480))
        self.gridLayout_6 = QtWidgets.QGridLayout(CompoundSpectraDialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(CompoundSpectraDialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(CompoundSpectraDialog)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(CompoundSpectraDialog)
        self.groupBox.setMaximumSize(QtCore.QSize(480, 240))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(311, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(CompoundSpectraDialog)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout_6.addWidget(self.closeButton, 2, 1, 1, 1)
        self.okButton = QtWidgets.QPushButton(CompoundSpectraDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout_6.addWidget(self.okButton, 2, 2, 1, 1)

        self.retranslateUi(CompoundSpectraDialog)
        QtCore.QMetaObject.connectSlotsByName(CompoundSpectraDialog)

    def retranslateUi(self, CompoundSpectraDialog):
        _translate = QtCore.QCoreApplication.translate
        CompoundSpectraDialog.setWindowTitle(_translate("CompoundSpectraDialog", "Compound spectra"))
        self.label.setText(_translate("CompoundSpectraDialog", "Name"))
        self.label_2.setText(_translate("CompoundSpectraDialog", "Precursor m/z"))
        self.label_4.setText(_translate("CompoundSpectraDialog", "Instrument type"))
        self.label_9.setText(_translate("CompoundSpectraDialog", "Ion mode"))
        self.label_8.setText(_translate("CompoundSpectraDialog", "Retention time"))
        self.label_10.setText(_translate("CompoundSpectraDialog", "Links"))
        self.label_3.setText(_translate("CompoundSpectraDialog", "Precursor type"))
        self.label_5.setText(_translate("CompoundSpectraDialog", "Instrument"))
        self.label_7.setText(_translate("CompoundSpectraDialog", "Collision energy"))
        self.label_6.setText(_translate("CompoundSpectraDialog", "SMILES"))
        self.label_11.setText(_translate("CompoundSpectraDialog", "Biological source"))
        self.groupBox.setTitle(_translate("CompoundSpectraDialog", "MS/MS spectra"))
        self.closeButton.setText(_translate("CompoundSpectraDialog", "Close"))
        self.okButton.setText(_translate("CompoundSpectraDialog", "OK"))

