mspfm.py : mspfilemanager.ui compoundspectra.ui
	pyuic5 compoundspectra.ui -o gui_compoundspectra.py
	pyuic5 mspfilemanager.ui -o gui_mspfilemanager.py
	pyuic5 msmscomparissondialog.ui -o gui_msmscomparissondialog.py
