"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

from os import getcwd
from pathlib import Path

APP = ['main.py']
APP_NAME = "MsMsSpectralAnalysis"
OPTIONS = {'argv_emulation': True,
           'bdist_base': str(Path(getcwd()).parent) + '/build',
           'dist_dir': str(Path(getcwd()).parent) +'/dist',
           'iconfile': '../icons/MsMsSpectralAnalysis.icns',
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'CFBundleGetInfoString': "Analyse, Edit, Modify and Compare your Ms/MS spectra",
               'CFBundleIdentifier': "com.metaunige.osx.msmsspectralanalysis",
               'CFBundleVersion': "0.1.0",
               'CFBundleShortVersionString': "0.1.0",
               'NSHumanReadableCopyright': u"Copyright 2017, Giuseppe Marco Randazzo, All Rights Reserved"
            }
          }

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
